In [31]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
wu = pd.read_csv('Warunk Upnormal Cempaka Putih_.csv')

In [4]:
wu.head()

Nama Toko              Nama Pelanggan        Waktu   \
0  Warunk Upnormal Cempaka Putih               Wanto Robusta  sebulan lalu   
1  Warunk Upnormal Cempaka Putih  Andrian Lutfiansyah Alfath  sebulan lalu   
2  Warunk Upnormal Cempaka Putih       Muhammad Rizky Rianto  9 bulan lalu   
3  Warunk Upnormal Cempaka Putih               Timeh Harahap  5 bulan lalu   
4  Warunk Upnormal Cempaka Putih           Kharisma Agustina  2 bulan lalu   

                                    review-full-text  Jtu6Td  
0  Keterangan di google maps, 24 jam. Ternyata cu...     NaN  
1  •tempat strategis, mudah ditemukan.•parkiran m...     NaN  
2  Warunk Upnormal itu warkop naik level dengan r...     NaN  
3  Makanannya ok, penyajiannya juga cepat.Lantai ...     NaN  
4  Tempatnya luas, enak buat kumpul sama temen". ...     NaN

In [8]:
target = wu.drop(['Nama Toko', 'Nama Pelanggan', 'Jtu6Td'], axis=1)

In [15]:
target.head(1)

Waktu                                    review-full-text
0  sebulan lalu  Keterangan di google maps, 24 jam. Ternyata cu...

In [19]:
target = wu[['review-full-text']]

In [20]:
target

review-full-text
0   Keterangan di google maps, 24 jam. Ternyata cu...
1   •tempat strategis, mudah ditemukan.•parkiran m...
2   Warunk Upnormal itu warkop naik level dengan r...
3   Makanannya ok, penyajiannya juga cepat.Lantai ...
4   Tempatnya luas, enak buat kumpul sama temen". ...
5   Tempatnya enak, luas, lega. Makanan dan minuma...
6   Saat saya berkunjung,  sistem pelayanannya men...
7   Malam ini pelayanan kurang baik.Mgkn krn banya...
8   Tempatnya nyaman, makanan nya enak. Pelayanan ...
9   Lantai 2 nya panas beneer, AC cuman jadi akses...
10  Lantai 2 nya panas beneer, AC cuman jadi akses...
11  Lokasinya tepat di jalan raya cempaka putih, s...
12        Menunya harus tambah inovasi lagi biar seru
13  Tempatnya nyaman buat ngerjain tugas, nongkron...
14  Tempatnya nyaman buat berlama2 ngerjain tugas,...
15  Pelayananya baik but so sorry, biasa aja makan...
16  Warung Upnormal ini terletak di Jalan Cempaka ...
17  Nggak kayak dulu nih tempat.. Menu nya tidak s...
18  Selalu suka jika datang ke upnormal...apalagi ...
19  Lantai 1 ademLantai 2 gak ada ACParkir relatif...
20  Makanannya lama dateng, minumannya lebih lama ...
21  Parkiran mobil sempit, jadi aku parkir di Indo...
22  Pesan nasi kulit sambal matah + susu Almond. R...
23  Tempatnya sih enak buat nongkrong cuman pelaya...
24  Harga sama rasa jauh, mending di warmindo sebe...
25  Dulu sih selalu penasaran pengen ksini. Tp par...
26  Tempatnya memang asik untuk nongkrong rame-ram...
27  Tempatnya strategis dan cukup cozy.  Sayangnya...
28  Tempatnya bagus banget, Instagramable. Untuk h...
29  Overall seperti warunk upnormal lainnya, tp sa...
30  Tempat yang asik untuk nongkrong dengan teman ...

In [21]:
target.shape

(31, 1)

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [25]:
dtm = cv.fit_transform(target['review-full-text'])

In [26]:
dtm

<31x201 sparse matrix of type '<class 'numpy.int64'>'
	with 704 stored elements in Compressed Sparse Row format>

LDA

In [27]:
from sklearn.decomposition import LatentDirichletAllocation

In [28]:
LDA = LatentDirichletAllocation(n_components=3, random_state=42)

In [29]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=3, random_state=42)

In [32]:
len(cv.get_feature_names())

201

In [37]:
import random
for i in range(5):
    random_word = random.randint(0,54776)
    print(cv.get_feature_names()[random_word])

['ac', 'ada', 'agak', 'aja', 'aksesoris', 'aku', 'almond', 'apalagi', 'asik', 'atas', 'atau', 'baik', 'bakar', 'bakarnya', 'bakso', 'banget', 'banyak', 'bareng', 'baru', 'beneer', 'berasa', 'berbagai', 'bersih', 'biasa', 'bilang', 'bisa', 'boedjangan', 'buat', 'bukan', 'cafe', 'cempaka', 'cepat', 'cireng', 'cocok', 'cozy', 'cuma', 'cuman', 'dan', 'dari', 'datang', 'deh', 'dengan', 'di', 'dia', 'dikasih', 'dimakan', 'ditanyain', 'dulu', 'emang', 'enak', 'ga', 'gak', 'gitu', 'goreng', 'gorengnya', 'harga', 'harganya', 'harus', 'indomaret', 'indomie', 'indomienya', 'ini', 'instagramable', 'itu', 'jadi', 'jalan', 'jalanan', 'jam', 'jd', 'jelek', 'jg', 'juga', 'kalau', 'kalo', 'karna', 'kartu', 'kasir', 'kasirnya', 'katanya', 'kaya', 'ke', 'kecil', 'keju', 'kerasa', 'ketika', 'kopi', 'kosan', 'kurang', 'lagi', 'lah', 'lainnya', 'lama', 'langsung', 'lantai', 'lebih', 'lokasinya', 'luas', 'lumayan', 'maaf', 'macam', 'mahal', 'makan', 'makanan', 'makanannya', 'malah', 'malam', 'masih', 'mau', 

In [42]:
random_word_id = random.randint(1, 10)
cv.get_feature_names()[random_word]

IndexError: list index out of range

In [43]:
len(LDA.components_)

3

In [44]:
LDA.components_

array([[ 0.33359947,  2.32197844,  2.81965734,  2.33001264,  0.33374475,
         0.33369044,  1.33155439,  3.34764326,  0.43415762,  0.33352132,
         0.33348088,  0.33348386,  0.33341427,  1.33349131,  0.33341094,
         8.37508769,  1.33535342,  1.08891392,  2.37108355,  0.33374475,
         0.33339642,  0.333472  ,  0.33356056,  1.3311131 ,  1.33201131,
         2.33640139,  0.33341201,  3.3357065 ,  2.32062222,  3.33315898,
         0.33344591,  0.33360565,  1.33369607,  0.43415135,  0.33347711,
         4.33051362,  2.34932291,  7.96632252,  1.33234035,  0.33354374,
         0.33354326,  3.33352067,  3.32410933,  1.33239044,  2.33420872,
         2.32054895,  1.35044444,  0.33392528,  2.33178368,  6.37136993,
         1.31702362,  0.3338258 ,  1.33217136,  0.38226824,  2.32059398,
         2.33527368,  0.33348286,  0.33458248,  0.333988  ,  1.33084307,
         1.33457323,  0.33357569,  1.3355837 ,  1.33188683,  2.92668855,
         0.33341133,  0.33352312,  0.33342688,  0.3

In [46]:
single_topic = LDA.components_[0]
top_word_indices = single_topic.argsort()[-10:]
for index in top_word_indices:
    print(cv.get_feature_names()[index])

ya
sih
tapi
ramah
juga
tempatnya
enak
nya
dan
banget


In [50]:
for index,topic in enumerate(LDA.components_):
    print(f'TOP 15 Kata #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

TOP 15 Kata #0
['nasi', 'rasa', 'cuma', 'jelek', 'pas', 'ya', 'sih', 'tapi', 'ramah', 'juga', 'tempatnya', 'enak', 'nya', 'dan', 'banget']


TOP 15 Kata #1
['putih', 'bakso', 'ini', 'upnormal', 'makanannya', 'tempatnya', 'panas', 'tp', 'juga', 'untuk', 'kurang', 'ga', 'di', 'lantai', 'dan']


TOP 15 Kata #2
['roti', 'nya', 'untuk', 'agak', 'menu', 'yg', 'dengan', 'di', 'tempat', 'buat', 'dan', 'saya', 'ada', 'yang', 'juga']




In [51]:
dtm.shape

(31, 201)

In [52]:
len(target)

31

In [53]:
topic_result = LDA.transform(dtm)

In [55]:
topic_result.shape

(31, 3)

In [56]:
topic_result[0]

array([0.00551522, 0.0054863 , 0.98899848])

In [60]:
topic_result[0].round(2)

array([0.01, 0.01, 0.99])

In [61]:
topic_result[0].argmax()

2

In [63]:
topic_result.argmax(axis=1)

array([2, 2, 2, 1, 0, 0, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2,
       0, 0, 0, 1, 0, 1, 0, 1, 2], dtype=int64)

In [64]:
target['Topic'] = topic_result.argmax(axis=1)

In [65]:
target

review-full-text  Topic
0   Keterangan di google maps, 24 jam. Ternyata cu...      2
1   •tempat strategis, mudah ditemukan.•parkiran m...      2
2   Warunk Upnormal itu warkop naik level dengan r...      2
3   Makanannya ok, penyajiannya juga cepat.Lantai ...      1
4   Tempatnya luas, enak buat kumpul sama temen". ...      0
5   Tempatnya enak, luas, lega. Makanan dan minuma...      0
6   Saat saya berkunjung,  sistem pelayanannya men...      2
7   Malam ini pelayanan kurang baik.Mgkn krn banya...      2
8   Tempatnya nyaman, makanan nya enak. Pelayanan ...      0
9   Lantai 2 nya panas beneer, AC cuman jadi akses...      1
10  Lantai 2 nya panas beneer, AC cuman jadi akses...      1
11  Lokasinya tepat di jalan raya cempaka putih, s...      1
12        Menunya harus tambah inovasi lagi biar seru      2
13  Tempatnya nyaman buat ngerjain tugas, nongkron...      2
14  Tempatnya nyaman buat berlama2 ngerjain tugas,...      2
15  Pelayananya baik but so sorry, biasa aja makan...      2
16  Warung Upnormal ini terletak di Jalan Cempaka ...      1
17  Nggak kayak dulu nih tempat.. Menu nya tidak s...      2
18  Selalu suka jika datang ke upnormal...apalagi ...      2
19  Lantai 1 ademLantai 2 gak ada ACParkir relatif...      1
20  Makanannya lama dateng, minumannya lebih lama ...      1
21  Parkiran mobil sempit, jadi aku parkir di Indo...      2
22  Pesan nasi kulit sambal matah + susu Almond. R...      0
23  Tempatnya sih enak buat nongkrong cuman pelaya...      0
24  Harga sama rasa jauh, mending di warmindo sebe...      0
25  Dulu sih selalu penasaran pengen ksini. Tp par...      1
26  Tempatnya memang asik untuk nongkrong rame-ram...      0
27  Tempatnya strategis dan cukup cozy.  Sayangnya...      1
28  Tempatnya bagus banget, Instagramable. Untuk h...      0
29  Overall seperti warunk upnormal lainnya, tp sa...      1
30  Tempat yang asik untuk nongkrong dengan teman ...      2